SELECT DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'YourTableName' AND COLUMN_NAME = 'YourColumnName';

-- ตัวอย่าง
SELECT COLUMN_NAME,DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Student' 
AND COLUMN_NAME = 'YourColumnName';